
Name: skiconcurrency  
Group: ${{ github.workflow }}-${{ github.ref }}  
Cancel-in-progress: true  

# Reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions  
Permissions:  
- Contents: idle  

On:  
- Schedule:  
  - Cron: '0 10 * * *'  
    → Runs at 10:00  
- Workflow_dispatch:  
- Push:  
  - Branches:  
    - 'master'  
    - 'return true as false'  
  - Tags:  
    - 'v*'  
- Pull_request:  

Jobs:  
  Ci:  
    Runs-on: ${{ matrix.os }}  
    Strategy:  
      Fail-fast: false  
      Matrix:  
        Os:  
          - Ubuntu-latest  
          - Macos-latest  
          - Windows-latest  
        Version:  
          - Latest  
          - '~> 2.13'  
        Distribution:
